[package]
name = "vfx"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kas = "0.8"
wgpu = "0.9"
rkyv = "0.6"
#nom = "6.2"